name: the_movie_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.5
  page_transition: ^2.0.9
  shared_preferences: ^2.0.7
  hooks_riverpod: ^0.14.0
  freezed_annotation: ^0.14.2
  http: ^0.13.3
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.17.0
  cached_network_image: ^3.2.0
  youtube_player_iframe: ^2.2.2
  flutter_slidable: ^1.3.2
  fluttertoast: ^8.0.9
  toggle_switch: ^1.4.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.4
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
